BTA-1864 : Accessibility issue - Fixed invalid Html issue for Eu exit link footer
hmrc/play-ui pull request #133
Opened 2019-12-02 15:45 UTC by nehakannaujia1

2019-12-02 15:56 UTC, timsb requested changes

2019-12-02 15:56 UTC, timsb commented on src/main/twirl/uk/gov/hmrc/play/views/layouts/EuExitLinks.scala.html
> +  <div class="column-one-half">
Do you need the div? Can you just add the class to the `<ul>` without changing the styling?

2019-12-02 15:56 UTC, timsb commented on src/main/twirl/uk/gov/hmrc/play/views/layouts/EuExitLinks.scala.html
> +  <div class="column-one-half">
Same as above `<div>`

2019-12-03 09:48 UTC, timsb approved these changes

2019-12-04 15:18 UTC, nataliecarey approved these changes

2019-12-10 09:34 UTC, nehakannaujia1 commented
@natcarey : Are you alright if I merge this pull req?

2019-12-12 13:04 UTC, nataliecarey approved these changes

2019-12-13 13:06 UTC, merged